apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scenario2
  template:
    metadata:
      labels:
        app: scenario2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
